name: E2E Tests

on:
  deployment_status:

jobs:
  tests:
    if: ${{ github.event.deployment_status.state == 'success' }}
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform: [ chrome-android, safari-ios, chrome-win, firefox-win ]
    steps:
      - name: Checkout (including submodules)
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'
      - name: Run tests
        env:
          MAIN_PAGE_URL: ${{ github.event.deployment_status.target_url }}
          SAUCELABS_USERNAME: ${{ secrets.SAUCELABS_USERNAME }}
          SAUCELABS_PASSWORD: ${{ secrets.SAUCELABS_PASSWORD }}
        run: |
          cd tests/e2e
          ./gradlew runStories -Pvividus.web-application.main-page-url=${MAIN_PAGE_URL} \
                               -Pvividus.selenium.grid.username=${SAUCELABS_USERNAME} \
                               -Pvividus.selenium.grid.password=${SAUCELABS_PASSWORD} \
                               -Pvividus.configuration-set.active=${{ matrix.platform }}
      - name: Publish web application tests report
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: Tests report for ${{ matrix.platform }} run
          path: tests/e2e/output/reports/allure
